name: On Commit action

on:
  push:
    branches: ["main"]
    
  workflow_dispatch:

jobs:
  test_actions:
    runs-on: ubuntu-latest
    container:
      image: nordicplayground/nrfconnect-sdk:main
      options: --cpus 2
    env:
      BASE_REF: ${{ github.base_ref }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Prepare directory
        run: |
          git config --global --add safe.directory /__w/sdk-sidewalk/sdk-sidewalk
          cp -r ../sdk-sidewalk /workdir/sidewalk
          cd /workdir/sidewalk
          #DEBUG
          ls -l
          git status
          git remote -v
          git log --oneline --graph  --all
